# .github/workflows/pages.yml
name: Build and Deploy Jekyll
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-ruby@v4
      - run: bundle install
      - run: bundle exec jekyll build -d ./_site
      - uses: actions/upload-pages-artifact@v3
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
